language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: true
cache:
  pip: true
  directories:
    - $HOME/downloads
    - /home/travis/build/tisto/solr-testing/downloads
env:
  - SOLR_VERSION=6.4.1
  - SOLR_VERSION=6.5.0
  - SOLR_VERSION=6.5.1
#matrix:
#  allow_failures:
#    - env: SOLR_VERSION=5.0.0
before_install:
  - mkdir -p $HOME/downloads
  - sed -ie "s#SOLR_VERSION := 6.5.0#SOLR_VERSION := $SOLR_VERSION#" Makefile
install:
  - make bootstrap
  - sudo pip install -r requirements.txt
  - sudo python setup.py develop
script:
  - py.test tests/
